/* Generated by the New Jersey Machine-Code Toolkit, version 0.5a */
/* command line: tools -verbose -encoder enc hppa9.spec hppadis.spec */
/* must #include <mclib.h> before this file */
extern void fid(int fmt, int r, int t);
extern void fcpy(int fmt, int r, int t);
extern void fabs(int fmt, int r, int t);
extern void fsqrt(int fmt, int r, int t);
extern void frnd(int fmt, int r, int t);
extern void fneg(int fmt, int r, int t);
extern void fnegabs(int fmt, int r, int t);
extern void fcnvff(int sf, int df, int r, int t);
extern void fcnvxf(int sf, int df, int r, int t);
extern void fcnvfxt(int sf, int df, int r, int t);
extern void flt_c2_0c(int fmt, int c, int r1, int r2);
extern void flt_c2_0e(unsigned /* [0..1] */ f_20, int c, int r1, int r2);
extern void flt_c3_0c(int fmt, int r1, int r2, int t);
extern void flt_c3_0e(int fmt, int r1, int r2, int t);
