/* Generated by the New Jersey Machine-Code Toolkit, version 0.5a */
/* command line: tools -debug-match dbm -matcher disassembler.m -decoder dec -encoder enc -verbose hppa.spec hppadis.spec */
/* must #include <mclib.h> before this file */
enum c_c_n_tag { c_c_neg_TAG = 2, c_c_nonneg_TAG = 1, };
typedef struct c_c_n_instance {
  int tag;
  union {
    struct {
      char avoid_empty_structures;
    } c_c_neg;
    struct {
      char avoid_empty_structures;
    } c_c_nonneg;
  } u;
} c_c_n_Instance;
enum c_c_tag { c_arith_dw_TAG = 7, c_arith_none_TAG = 8, c_arith_w_TAG = 6, 
  c_bbs_dw_TAG = 5, c_bbs_w_TAG = 4, c_cmpb_dw_TAG = 2, c_cmpb_w_TAG = 1, 
  c_cmpib_dw_TAG = 3, c_sep_TAG = 9, };
typedef struct c_c_instance {
  int tag;
  union {
    struct {
      unsigned c3_16:3;
      c_c_n_Instance  c_c_n;
    } c_arith_dw;
    struct {
      char avoid_empty_structures;
    } c_arith_none;
    struct {
      unsigned c3_16:3;
      c_c_n_Instance  c_c_n;
    } c_arith_w;
    struct {
      unsigned c_16:1;
    } c_bbs_dw;
    struct {
      unsigned c_16:1;
    } c_bbs_w;
    struct {
      unsigned c3_16:3;
      c_c_n_Instance  c_c_n;
    } c_cmpb_dw;
    struct {
      unsigned c3_16:3;
      c_c_n_Instance  c_c_n;
    } c_cmpb_w;
    struct {
      int cond;
    } c_cmpib_dw;
    struct {
      int cond;
    } c_sep;
  } u;
} c_c_Instance;
enum c_null_tag { c_br_nnull_TAG = 1, c_br_null_TAG = 2, };
typedef struct c_null_instance {
  int tag;
  union {
    struct {
      char avoid_empty_structures;
    } c_br_nnull;
    struct {
      char avoid_empty_structures;
    } c_br_null;
  } u;
} c_null_Instance;
enum c_wcr_tag { c_mfctl_TAG = 2, c_mfctl_w_TAG = 1, };
typedef struct c_wcr_instance {
  int tag;
  union {
    struct {
      unsigned r_06:5;
    } c_mfctl;
    struct {
      char avoid_empty_structures;
    } c_mfctl_w;
  } u;
} c_wcr_Instance;
enum c_bit_tag { c_bitpos_w_TAG = 1, c_bitsar_TAG = 2, };
typedef struct c_bit_instance {
  int tag;
  union {
    struct {
      unsigned p_06:5;
    } c_bitpos_w;
    struct {
      char avoid_empty_structures;
    } c_bitsar;
  } u;
} c_bit_Instance;
enum c_addr_tag { c_l_addr_none_TAG = 10, c_s_addr_ma_TAG = 2, 
  c_s_addr_mb_TAG = 1, c_s_addr_notm_TAG = 3, c_x_addr_m_TAG = 4, 
  c_x_addr_notm_TAG = 5, c_y_addr_e_TAG = 6, c_y_addr_m_TAG = 7, 
  c_y_addr_me_TAG = 8, c_y_addr_none_TAG = 9, };
typedef struct c_addr_instance {
  int tag;
  union {
    struct {
      char avoid_empty_structures;
    } c_l_addr_none;
    struct {
      char avoid_empty_structures;
    } c_s_addr_ma;
    struct {
      char avoid_empty_structures;
    } c_s_addr_mb;
    struct {
      char avoid_empty_structures;
    } c_s_addr_notm;
    struct {
      char avoid_empty_structures;
    } c_x_addr_m;
    struct {
      char avoid_empty_structures;
    } c_x_addr_notm;
    struct {
      char avoid_empty_structures;
    } c_y_addr_e;
    struct {
      char avoid_empty_structures;
    } c_y_addr_m;
    struct {
      char avoid_empty_structures;
    } c_y_addr_me;
    struct {
      char avoid_empty_structures;
    } c_y_addr_none;
  } u;
} c_addr_Instance;
enum c_xd_tag { l_addr_16_old_TAG = 8, l_addr_17_old_TAG = 9, 
  s_addr_im_r_TAG = 6, s_addr_r_im_TAG = 7, x_addr_nots_TAG = 1, 
  x_addr_s_byte_TAG = 2, x_addr_s_dwrd_TAG = 5, x_addr_s_hwrd_TAG = 3, 
  x_addr_s_word_TAG = 4, };
typedef struct c_xd_instance {
  int tag;
  union {
    struct {
      int ldisp;
    } l_addr_16_old;
    struct {
      int ldisp;
    } l_addr_17_old;
    struct {
      int im5;
    } s_addr_im_r;
    struct {
      int im5;
    } s_addr_r_im;
    struct {
      int x;
    } x_addr_nots;
    struct {
      int x;
    } x_addr_s_byte;
    struct {
      int x;
    } x_addr_s_dwrd;
    struct {
      int x;
    } x_addr_s_hwrd;
    struct {
      int x;
    } x_addr_s_word;
  } u;
} c_xd_Instance;
extern c_c_n_Instance c_c_nonneg(void);
extern c_c_n_Instance c_c_neg(void);
extern c_c_Instance c_cmpb_w(unsigned /* [0..7] */ c3_16, c_c_n_Instance c_c_n);
extern c_c_Instance c_cmpb_dw(unsigned /* [0..7] */ c3_16, c_c_n_Instance c_c_n);
extern c_c_Instance c_cmpib_dw(int cond);
extern c_c_Instance c_bbs_w(unsigned /* [0..1] */ c_16);
extern c_c_Instance c_bbs_dw(unsigned /* [0..1] */ c_16);
extern c_c_Instance c_arith_w(unsigned /* [0..7] */ c3_16, c_c_n_Instance c_c_n);
extern c_c_Instance c_arith_dw(unsigned /* [0..7] */ c3_16, c_c_n_Instance c_c_n);
extern c_c_Instance c_arith_none(void);
extern c_c_Instance c_sep(int cond);
extern c_null_Instance c_br_nnull(void);
extern c_null_Instance c_br_null(void);
extern c_wcr_Instance c_mfctl_w(void);
extern c_wcr_Instance c_mfctl(unsigned /* [0..31] */ r_06);
extern c_bit_Instance c_bitpos_w(unsigned /* [0..31] */ p_06);
extern c_bit_Instance c_bitsar(void);
extern c_addr_Instance c_s_addr_mb(void);
extern c_addr_Instance c_s_addr_ma(void);
extern c_addr_Instance c_s_addr_notm(void);
extern c_addr_Instance c_x_addr_m(void);
extern c_addr_Instance c_x_addr_notm(void);
extern c_addr_Instance c_y_addr_e(void);
extern c_addr_Instance c_y_addr_m(void);
extern c_addr_Instance c_y_addr_me(void);
extern c_addr_Instance c_y_addr_none(void);
extern c_addr_Instance c_l_addr_none(void);
extern c_xd_Instance x_addr_nots(int x);
extern c_xd_Instance x_addr_s_byte(int x);
extern c_xd_Instance x_addr_s_hwrd(int x);
extern c_xd_Instance x_addr_s_word(int x);
extern c_xd_Instance x_addr_s_dwrd(int x);
extern c_xd_Instance s_addr_im_r(int im5);
extern c_xd_Instance s_addr_r_im(int im5);
extern c_xd_Instance l_addr_16_old(int ldisp);
extern c_xd_Instance l_addr_17_old(int ldisp);
extern void NOP(void);
extern void COPY(unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ t_27);
extern void ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ADD_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ADD_c(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ADD_c_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL1ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL1ADD_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL2ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL2ADD_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL3ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL3ADD_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB_t(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB_t_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB_b(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SUB_b_v(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void DS(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ANDCM(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void AND(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void OR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void XOR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void UXOR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void CMPCLR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void UADDCM(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void UADDCMT(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ADD_l(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL1ADD_l(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL2ADD_l(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void SHL3ADD_l(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void DCOR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void IDCOR(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HADD_s(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HADD_u(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSUB(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSUB_s(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSUB_u(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HAVG(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHL1ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHL2ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHL3ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHR1ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHR2ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void HSHR3ADD(c_c_Instance c_c, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_27);
extern void ADDI(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void ADDI_v(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void ADDI_t(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void ADDI_t_v(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void SUBI(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void SUBI_v(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void CMPICLR(c_c_Instance c_c, int imm11, unsigned /* [0..31] */ r_06, unsigned /* [0..31] */ t_11);
extern void ADDIL(int imm21, unsigned /* [0..31] */ r_06);
extern void LDBX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDHX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDWX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDDX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDDAX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDWAX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDCDX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDCWX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDBS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDHS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDWS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDDS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDDAS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDWAS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDCDS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void LDCWS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void STBS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STHS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STWS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STDS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STWAS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STWDS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STBYS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STDBYS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void FLDDX(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void FLDDS(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void FSTDX(c_addr_Instance c_addr, unsigned /* [0..31] */ r_27, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void FSTDS(c_addr_Instance c_addr, unsigned /* [0..31] */ r_27, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void FLDWX(c_addr_Instance c_addr, c_xd_Instance c_xd, int s, int b, int treg);
extern void FLDWS(c_addr_Instance c_addr, c_xd_Instance c_xd, int s, int b, int treg);
extern void FSTWX(c_addr_Instance c_addr, int rreg, c_xd_Instance c_xd, int s, int b);
extern void FSTWS(c_addr_Instance c_addr, int rreg, c_xd_Instance c_xd, int s, int b);
extern void LDB(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_11);
extern void LDH(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_11);
extern void LDW(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_11);
extern void LDWM(c_addr_Instance c_addr, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_11);
extern void STB(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STH(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STW(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void STWM(c_addr_Instance c_addr, unsigned /* [0..31] */ r_11, c_xd_Instance c_xd, unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06);
extern void LDO(int ldisp, int b, int t);
extern void LDIL(int imm21, unsigned /* [0..31] */ t_06);
extern void VSHD(int r1, int r2, int t, c_c_Instance c_c);
extern void SHD(int r1, int r2, int p, int t, c_c_Instance c_c);
extern void VEXTRU(int r, int len, int t, c_c_Instance c_c);
extern void VEXTRS(int r, int len, int t, c_c_Instance c_c);
extern void EXTRU(int r, int p, int len, int t, c_c_Instance c_c);
extern void EXTRS(int r, int p, int len, int t, c_c_Instance c_c);
extern void VDEP(int r, int len, int t, c_c_Instance c_c);
extern void ZVDEP(int r, int len, int t, c_c_Instance c_c);
extern void DEP(int r, int p, int len, int t, c_c_Instance c_c);
extern void ZDEP(int r, int p, int len, int t, c_c_Instance c_c);
extern void VDEPI(int i, int len, int t, c_c_Instance c_c);
extern void ZVDEPI(int i, int len, int t, c_c_Instance c_c);
extern void DEPI(int i, int p, int len, int t, c_c_Instance c_c);
extern void ZDEPI(int i, int p, int len, int t, c_c_Instance c_c);
extern void BL(c_null_Instance c_null, int ubr_target, unsigned /* [0..31] */ t_06);
extern void GATE(c_null_Instance c_null, int ubr_target, unsigned /* [0..31] */ t_06);
extern void BL_PUSH(c_null_Instance c_null, int ubr_target, unsigned /* [0..31] */ t_06);
extern void BL_LONG(c_null_Instance c_null, int ubr_target);
extern void BLR(c_null_Instance c_null, unsigned /* [0..31] */ x_11, unsigned /* [0..31] */ t_06);
extern void BV(c_null_Instance c_null, unsigned /* [0..31] */ x_11, unsigned /* [0..31] */ b_06);
extern void BVE(unsigned /* [0..1] */ p_31, c_null_Instance c_null, unsigned /* [0..31] */ b_06);
extern void BVE_l(unsigned /* [0..1] */ p_31, c_null_Instance c_null, unsigned /* [0..31] */ b_06);
extern void BREAK(unsigned /* [0..31] */ im5_27, unsigned /* [0..8191] */ im13_06);
extern void SSM(unsigned /* [0..1023] */ im10_06, unsigned /* [0..31] */ t_27);
extern void RSM(unsigned /* [0..1023] */ im10_06, unsigned /* [0..31] */ t_27);
extern void RFI(void);
extern void RFI_r(void);
extern void SYNC(void);
extern void SYNCDMA(void);
extern void MTSM(unsigned /* [0..31] */ r_11);
extern void MTSARCM(unsigned /* [0..31] */ r_11);
extern void MFCTL(c_wcr_Instance c_wcr, unsigned /* [0..31] */ t_27);
extern void MFCTL_w(c_wcr_Instance c_wcr, unsigned /* [0..31] */ t_27);
extern void MTCTL(unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ cr_06);
extern void MFIA(unsigned /* [0..31] */ t_27);
extern void LDSID(unsigned /* [0..3] */ s2_16, unsigned /* [0..31] */ b_06, unsigned /* [0..31] */ t_27);
extern void MTSP(unsigned /* [0..31] */ r_11, int sr);
extern void MFSP(int sr, unsigned /* [0..31] */ t_27);
extern void ADDBT(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void ADDBF(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void ADDIBT(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void ADDIBF(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void MOVB(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void MOVIB(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void CMPBT(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void CMPBF(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void CMPBdwt(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void CMPBdwf(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, unsigned /* [0..31] */ r_06, int target);
extern void CMPIBT(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void CMPIBF(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void cmpib_dw(c_c_Instance c_c, c_null_Instance c_null, int im5, unsigned /* [0..31] */ r_06, int target);
extern void BB(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, c_bit_Instance c_bit, int target);
extern void BVB(c_c_Instance c_c, c_null_Instance c_null, unsigned /* [0..31] */ r_11, c_bit_Instance c_bit, int target);
extern void FID(int fmt, int r, int t);
extern void FCPY(int fmt, int r, int t);
extern void FABS(int fmt, int r, int t);
extern void FSQRT(int fmt, int r, int t);
extern void FRND(int fmt, int r, int t);
extern void FNEG(int fmt, int r, int t);
extern void FNEGABS(int fmt, int r, int t);
extern void FCPY_E(int f, int r, int t);
extern void FABS_E(int f, int r, int t);
extern void FSQRT_E(int f, int r, int t);
extern void FRND_E(int f, int r, int t);
extern void FNEG_E(int f, int r, int t);
extern void FNEGABS_E(int f, int r, int t);
extern void FCNVFF(int sf, int df, int r, int t);
extern void FCNVXF(int sf, int df, int r, int t);
extern void FCNVFX(int sf, int df, int r, int t);
extern void FCNVFXT(int sf, int df, int r, int t);
extern void FCNVFF_E(int sf, int df, int r, int t);
extern void FCNVXF_E(int sf, int df, int r, int t);
extern void FCNVFX_E(int sf, int df, int r, int t);
extern void FCNVFXT_E(int sf, int df, int r, int t);
extern void FCMP(int fmt, int c, int r1, int r2);
extern void FTEST(int fmt, int c, int r1, int r2);
extern void FCMP_E(unsigned /* [0..1] */ f_20, int c, int r1, int r2);
extern void FTEST_E(unsigned /* [0..1] */ f_20, int c, int r1, int r2);
extern void FADD(int fmt, int r1, int r2, int t);
extern void FSUB(int fmt, int r1, int r2, int t);
extern void FMPY(int fmt, int r1, int r2, int t);
extern void FDIV(int fmt, int r1, int r2, int t);
extern void FADD_E(int fmt, int r1, int r2, int t);
extern void FSUB_E(int fmt, int r1, int r2, int t);
extern void FMPY_E(int fmt, int r1, int r2, int t);
extern void FDIV_E(int fmt, int r1, int r2, int t);
extern void XMPYU(int r1, int r2, int t);
