/* Generated by the New Jersey Machine-Code Toolkit, version 0.5a */
/* command line: tools -debug-match dbm -matcher disassembler.2.m -decoder dec -encoder enc -verbose hppa.2.spec hppadis.spec */
#include <mclib.h>
#include "enc.h"
#define sign_extend(N,SIZE) \
  (((int)((N) << (sizeof(unsigned)*8-(SIZE)))) >> (sizeof(unsigned)*8-(SIZE)))
/**************

c_cmpb_w c3_16 is 
  (COMBT) op == 32 & c3_16 = c3_16 
  | (COMBF) op == 34 & c3_16 = c3_16 
  | (COMIBT) op == 33 & c3_16 = c3_16 
  | (COMIBF) op == 35 & c3_16 = c3_16

***********/
c_c_Instance c_cmpb_w(unsigned /* [0..7] */ c3_16) {
  c_c_Instance _i = { c_cmpb_w_TAG };
  if (!((unsigned)(c3_16) < 0x8)) 
    (*fail) ("c3_16 = %d won't fit in 3 unsigned bits");
  _i.u.c_cmpb_w.c3_16 = c3_16;
  return _i;
}
/**************

c_cmpb_dw c3_16 is 
  (CMPBdwt) op == 39 & c3_16 = c3_16 
  | (CMPBdwf) op == 47 & c3_16 = c3_16 
  | (CMPIBdw) op == 59 & c3_16 = c3_16

***********/
c_c_Instance c_cmpb_dw(unsigned /* [0..7] */ c3_16) {
  c_c_Instance _i = { c_cmpb_dw_TAG };
  if (!((unsigned)(c3_16) < 0x8)) 
    (*fail) ("c3_16 = %d won't fit in 3 unsigned bits");
  _i.u.c_cmpb_dw.c3_16 = c3_16;
  return _i;
}
/**************

c_bbs_w c_16 is 
  (ins_bbs_w) op == 49 & d_18 ==  0 & c_16 = c_16 
  | (ins_bbs_w) op == 48 & d_18 ==  0 & c_16 = c_16

***********/
c_c_Instance c_bbs_w(unsigned /* [0..1] */ c_16) {
  c_c_Instance _i = { c_bbs_w_TAG };
  if (!((unsigned)(c_16) < 0x2)) 
    (*fail) ("c_16 = %d won't fit in 1 unsigned bits");
  _i.u.c_bbs_w.c_16 = c_16;
  return _i;
}
/**************

c_bbs_dw c_16 is 
  (ins_bbs_dw) op == 49 & d_18 ==  1 & c_16 = c_16 
  | (ins_bbs_dw) op == 48 & d_18 ==  1 & c_16 = c_16

***********/
c_c_Instance c_bbs_dw(unsigned /* [0..1] */ c_16) {
  c_c_Instance _i = { c_bbs_dw_TAG };
  if (!((unsigned)(c_16) < 0x2)) 
    (*fail) ("c_16 = %d won't fit in 1 unsigned bits");
  _i.u.c_bbs_dw.c_16 = c_16;
  return _i;
}
/**************

c_arith_w c3_16 is 
  (arith_w) op ==  2 & ext6_20 == 24 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 56 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 28 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 60 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 25 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 57 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 26 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 58 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 27 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 59 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 16 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 48 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 19 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 51 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 20 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 52 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 17 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  0 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  8 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  9 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 10 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 14 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 34 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 38 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 39 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 40 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 41 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 42 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 43 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 46 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 47 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 15 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 13 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 12 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  7 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  5 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 ==  4 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 11 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 29 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 30 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 31 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 21 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 22 & d_26 ==  0 & c3_16 = c3_16 
  | (arith_w) op ==  2 & ext6_20 == 23 & d_26 ==  0 & c3_16 = c3_16 
  | (ADDI) op == 45 & ext_20 ==  0 & c3_16 = c3_16 
  | (ADDI.v) op == 45 & ext_20 ==  1 & c3_16 = c3_16 
  | (ADDI.t) op == 44 & ext_20 ==  0 & c3_16 = c3_16 
  | (ADDI.t.v) op == 44 & ext_20 ==  1 & c3_16 = c3_16 
  | (SUBI) op == 37 & ext_20 ==  0 & c3_16 = c3_16 
  | (SUBI.v) op == 37 & ext_20 ==  1 & c3_16 = c3_16

***********/
c_c_Instance c_arith_w(unsigned /* [0..7] */ c3_16) {
  c_c_Instance _i = { c_arith_w_TAG };
  if (!((unsigned)(c3_16) < 0x8)) 
    (*fail) ("c3_16 = %d won't fit in 3 unsigned bits");
  _i.u.c_arith_w.c3_16 = c3_16;
  return _i;
}
/**************

c_arith_dw c3_16 is 
  (arith_dw) op ==  2 & ext6_20 == 24 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 56 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 28 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 60 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 25 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 57 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 26 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 58 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 27 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 59 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 16 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 48 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 19 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 51 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 20 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 52 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 17 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  0 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  8 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  9 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 10 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 14 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 34 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 38 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 39 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 40 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 41 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 42 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 43 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 46 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 47 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 15 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 13 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 12 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  7 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  5 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 ==  4 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 11 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 29 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 30 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 31 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 21 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 22 & d_26 ==  1 & c3_16 = c3_16 
  | (arith_dw) op ==  2 & ext6_20 == 23 & d_26 ==  1 & c3_16 = c3_16

***********/
c_c_Instance c_arith_dw(unsigned /* [0..7] */ c3_16) {
  c_c_Instance _i = { c_arith_dw_TAG };
  if (!((unsigned)(c3_16) < 0x8)) 
    (*fail) ("c3_16 = %d won't fit in 3 unsigned bits");
  _i.u.c_arith_dw.c3_16 = c3_16;
  return _i;
}
/**************

c_arith_none  is (ins_arith_none) op == 10

***********/
c_c_Instance c_arith_none(void) {
  c_c_Instance _i = { c_arith_none_TAG };
  return _i;
}
/**************

c_addrs  is 
  (ins_def_d) op ==  3 & ext4_22 ==  0 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  1 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  2 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  3 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  5 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  7 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  4 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  6 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  8 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 ==  9 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 == 10 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 == 11 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 == 14 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op ==  3 & ext4_22 == 15 & addr_19 ==  1 & m_26 ==  0 
  | (ins_def_d) op == 20 & ext_30 ==  0 & m_28 ==  0 
  | (ins_def_d) op == 28 & ext_30 ==  0 & m_28 ==  0 
  | (LDBl) op == 16 
  | (LDHl) op == 17 
  | (LDWl) op == 18 
  | (LDWlm2i) op == 23 & ext_29 ==  1 
  | (LDWlm) op == 19 
  | (LDO) op == 13 
  | (STBl) op == 24 
  | (STHl) op == 25 
  | (STWl) op == 26 
  | (STWlm2i) op == 31 & ext_29 ==  1 
  | (STWlm) op == 27 
  | (ins_ma) op ==  3 & ext4_22 ==  0 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  1 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  2 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  3 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  5 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  7 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  4 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  6 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_11  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  8 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op ==  3 & ext4_22 ==  9 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op ==  3 & ext4_22 == 10 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op ==  3 & ext4_22 == 11 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op ==  3 & ext4_22 == 14 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op ==  3 & ext4_22 == 15 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 &  1 <= im5_27  < 32 
  | (ins_ma) op == 20 & ext_30 ==  0 & m_28 ==  1 & a_29 ==  0 
  | (ins_mb) op ==  3 & ext4_22 ==  0 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  1 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  2 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  3 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  5 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  7 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  4 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  6 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  8 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 ==  9 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 == 10 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 == 11 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 == 14 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op ==  3 & ext4_22 == 15 & addr_19 ==  1 & m_26 ==  1 & a_18 ==  1 
  | (ins_mb) op == 20 & ext_30 ==  0 & m_28 ==  1 & a_29 ==  1 
  | (ins_o) op ==  3 & ext4_22 ==  0 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  1 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  2 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  3 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  5 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  7 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  4 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  6 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_11 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  8 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op ==  3 & ext4_22 ==  9 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op ==  3 & ext4_22 == 10 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op ==  3 & ext4_22 == 11 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op ==  3 & ext4_22 == 14 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op ==  3 & ext4_22 == 15 & addr_19 ==  1 & m_26 ==  1 & 
  a_18 ==  0 & im5_27 ==  0 
  | (ins_o) op == 20 & ext_30 ==  0 & m_28 ==  1 & a_29 ==  0 & im10_18 ==  0 
  | (ins_bm) op ==  3 & ext4_22 == 12 & addr_19 ==  1 & a_18 ==  0 & m_26 ==  1 
  | (ins_bm) op ==  3 & ext4_22 == 13 & addr_19 ==  1 & a_18 ==  0 & m_26 ==  1 
  | (ins_e) op ==  3 & ext4_22 == 12 & addr_19 ==  1 & a_18 ==  1 & m_26 ==  0 
  | (ins_e) op ==  3 & ext4_22 == 13 & addr_19 ==  1 & a_18 ==  1 & m_26 ==  0 
  | (ins_em) op ==  3 & ext4_22 == 12 & addr_19 ==  1 & a_18 ==  1 & m_26 ==  1 
  | (ins_em) op ==  3 & ext4_22 == 13 & addr_19 ==  1 & a_18 ==  1 & m_26 ==  1 
  | (ins_b) op ==  3 & ext4_22 == 12 & addr_19 ==  1 & a_18 ==  0 & m_26 ==  0 
  | (ins_b) op ==  3 & ext4_22 == 13 & addr_19 ==  1 & a_18 ==  0 & m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  0 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  1 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  2 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  3 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  5 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  7 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  4 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_def_il) op ==  3 & ext4_22 ==  6 & addr_19 ==  0 & u_18 ==  0 & 
  m_26 ==  0 
  | (ins_m) op ==  3 & ext4_22 ==  0 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  1 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  2 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  3 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  5 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  7 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  4 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_m) op ==  3 & ext4_22 ==  6 & addr_19 ==  0 & u_18 ==  0 & m_26 ==  1 
  | (ins_s) op ==  3 & ext4_22 ==  0 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  1 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  2 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  3 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  5 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  7 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  4 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_s) op ==  3 & ext4_22 ==  6 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  0 
  | (ins_sm) op ==  3 & ext4_22 ==  0 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  1 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  2 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  3 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  5 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  7 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  4 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1 
  | (ins_sm) op ==  3 & ext4_22 ==  6 & addr_19 ==  0 & u_18 ==  1 & m_26 ==  1

***********/
c_addr_Instance c_addrs(void) {
  c_addr_Instance _i = { c_addrs_TAG };
  return _i;
}
/**************

c_br_nnull  is 
  (ins_br_nnull) op == 58 & n_30 ==  0 
  | (ins_br_nnull) op == 32 & n_30 ==  0 
  | (ins_br_nnull) op == 34 & n_30 ==  0 
  | (ins_br_nnull) op == 39 & n_30 ==  0 
  | (ins_br_nnull) op == 47 & n_30 ==  0 
  | (ins_br_nnull) op == 33 & n_30 ==  0 
  | (ins_br_nnull) op == 35 & n_30 ==  0 
  | (ins_br_nnull) op == 59 & n_30 ==  0 
  | (ins_br_nnull) op == 49 & n_30 ==  0 
  | (ins_br_nnull) op == 48 & n_30 ==  0 
  | (ins_br_nnull) op == 56 & n_30 ==  0 
  | (ins_br_nnull) op == 57 & n_30 ==  0

***********/
c_null_Instance c_br_nnull(void) {
  c_null_Instance _i = { c_br_nnull_TAG };
  return _i;
}
/**************

c_br_null  is 
  (ins_br_null) op == 58 & n_30 ==  1 
  | (ins_br_null) op == 32 & n_30 ==  1 
  | (ins_br_null) op == 34 & n_30 ==  1 
  | (ins_br_null) op == 39 & n_30 ==  1 
  | (ins_br_null) op == 47 & n_30 ==  1 
  | (ins_br_null) op == 33 & n_30 ==  1 
  | (ins_br_null) op == 35 & n_30 ==  1 
  | (ins_br_null) op == 59 & n_30 ==  1 
  | (ins_br_null) op == 49 & n_30 ==  1 
  | (ins_br_null) op == 48 & n_30 ==  1 
  | (ins_br_null) op == 56 & n_30 ==  1 
  | (ins_br_null) op == 57 & n_30 ==  1

***********/
c_null_Instance c_br_null(void) {
  c_null_Instance _i = { c_br_null_TAG };
  return _i;
}
/**************

c_mfctl_w  is (MFCTL.w) op ==  0 & ext8_19 == 69 & ext_17 ==  1

***********/
c_wcr_Instance c_mfctl_w(void) {
  c_wcr_Instance _i = { c_mfctl_w_TAG };
  return _i;
}
/**************

c_mfctl r_06 is (MFCTL) op ==  0 & ext8_19 == 69 & ext_17 ==  0 & r_06 = r_06

***********/
c_wcr_Instance c_mfctl(unsigned /* [0..31] */ r_06) {
  c_wcr_Instance _i = { c_mfctl_TAG };
  if (!((unsigned)(r_06) < 0x20)) 
    (*fail) ("r_06 = %d won't fit in 5 unsigned bits");
  _i.u.c_mfctl.r_06 = r_06;
  return _i;
}
/**************

c_bitpos_w p_06 is (ins_bb_w) op == 49 & d_18 ==  0 & p_06 = p_06

***********/
c_bit_Instance c_bitpos_w(unsigned /* [0..31] */ p_06) {
  c_bit_Instance _i = { c_bitpos_w_TAG };
  if (!((unsigned)(p_06) < 0x20)) 
    (*fail) ("p_06 = %d won't fit in 5 unsigned bits");
  _i.u.c_bitpos_w.p_06 = p_06;
  return _i;
}
/**************

c_bitpos_dw p_06 is (ins_bb_dw) op == 49 & d_18 ==  1 & p_06 = p_06

***********/
c_bit_Instance c_bitpos_dw(unsigned /* [0..31] */ p_06) {
  c_bit_Instance _i = { c_bitpos_dw_TAG };
  if (!((unsigned)(p_06) < 0x20)) 
    (*fail) ("p_06 = %d won't fit in 5 unsigned bits");
  _i.u.c_bitpos_dw.p_06 = p_06;
  return _i;
}
/**************

c_bitsar  is (BVB) op == 48

***********/
c_bit_Instance c_bitsar(void) {
  c_bit_Instance _i = { c_bitsar_TAG };
  return _i;
}
/**************

index_addr x(ss,b)[c_addr] is 
  
  CASE c_addr OF 
  | c_addrs => 
      (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  0 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  0 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  0 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  0 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  1 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  1 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  1 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  1 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  2 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  2 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  2 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  2 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  3 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  3 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  3 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  3 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  5 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  5 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  5 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  5 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  7 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  7 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  7 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  7 & addr_19 ==  0 & x_11 = x & s2_16 = ss & b_06 = b
  END (* c_addr *)

***********/
addr_Instance index_addr(int x, int ss, int b, c_addr_Instance c_addr) {
  addr_Instance _i = { index_addr_TAG };
  _i.u.index_addr.x = x;
  _i.u.index_addr.ss = ss;
  _i.u.index_addr.b = b;
  _i.u.index_addr.c_addr = c_addr;
  return _i;
}
/**************

indexabs_addr x(b)[c_addr] is 
  
  CASE c_addr OF 
  | c_addrs => 
      (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  4 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  4 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  4 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  4 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  6 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  0 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  6 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  0 & op ==  3 & 
      ext4_22 ==  6 & addr_19 ==  0 & x_11 = x & b_06 = b 
      | (?noname?) (?c_addr:): u_18 ==  1 & m_26 ==  1 & op ==  3 & 
      ext4_22 ==  6 & addr_19 ==  0 & x_11 = x & b_06 = b
  END (* c_addr *)

***********/
addr_Instance indexabs_addr(int x, int b, c_addr_Instance c_addr) {
  addr_Instance _i = { indexabs_addr_TAG };
  _i.u.indexabs_addr.x = x;
  _i.u.indexabs_addr.b = b;
  _i.u.indexabs_addr.c_addr = c_addr;
  return _i;
}
/**************

