/* Generated by the New Jersey Machine-Code Toolkit, version 0.5a */
/* command line: tools -debug-match dbm -matcher disassembler.m -decoder dec -encoder enc -verbose hppa.spec hppadis.spec */
#include <mclib.h>
#include "enc.h"
#define sign_extend(N,SIZE) \
  (((int)((N) << (sizeof(unsigned)*8-(SIZE)))) >> (sizeof(unsigned)*8-(SIZE)))
/**************

c_c_nonneg  is 
  (CMPBT) op == 32 
  | (CMPBdwt) op == 39 
  | (CMPIBT) op == 33 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 24 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 56 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 28 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 60 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 25 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 57 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 26 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 58 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 27 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 59 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 16 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 48 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 19 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 51 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 20 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 52 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 17 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  0 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  8 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  9 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 10 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 14 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 34 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 38 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 39 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 40 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 41 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 42 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 43 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 46 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 47 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 15 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 13 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 12 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  7 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  5 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 ==  4 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 11 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 29 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 30 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 31 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 21 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 22 & f_19 ==  0 
  | (ins_br_nonneg) op ==  2 & ext6_20 == 23 & f_19 ==  0 
  | (ins_br_nonneg) op == 45 & ext_20 ==  0 & f_19 ==  0 
  | (ins_br_nonneg) op == 45 & ext_20 ==  1 & f_19 ==  0 
  | (ins_br_nonneg) op == 44 & ext_20 ==  0 & f_19 ==  0 
  | (ins_br_nonneg) op == 44 & ext_20 ==  1 & f_19 ==  0 
  | (ins_br_nonneg) op == 37 & ext_20 ==  0 & f_19 ==  0 
  | (ins_br_nonneg) op == 37 & ext_20 ==  1 & f_19 ==  0 
  | (ins_br_nonneg) op == 36 & f_19 ==  0 
  | (ADDBT) op == 40 
  | (ADDIBT) op == 41 
  | (ins_br_nonneg) op == 50 & c1_16 ==  0 
  | (ins_br_nonneg) op == 51 & c1_16 ==  0 
  | (ins_br_nonneg) op == 59 & c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 52 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  0 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  1 & 
  c1_16 ==  0 
  | (ins_br_nonneg) op == 53 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  0 & 
  c1_16 ==  0

***********/
c_c_n_Instance c_c_nonneg(void) {
  c_c_n_Instance _i = { c_c_nonneg_TAG };
  return _i;
}
/**************

c_c_neg  is 
  (CMPBF) op == 34 
  | (CMPBdwf) op == 47 
  | (CMPIBF) op == 35 
  | (ins_br_neg) op ==  2 & ext6_20 == 24 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 56 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 28 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 60 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 25 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 57 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 26 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 58 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 27 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 59 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 16 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 48 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 19 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 51 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 20 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 52 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 17 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  0 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  8 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  9 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 10 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 14 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 34 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 38 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 39 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 40 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 41 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 42 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 43 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 46 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 47 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 15 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 13 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 12 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  7 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  5 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 ==  4 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 11 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 29 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 30 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 31 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 21 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 22 & f_19 ==  1 
  | (ins_br_neg) op ==  2 & ext6_20 == 23 & f_19 ==  1 
  | (ins_br_neg) op == 45 & ext_20 ==  0 & f_19 ==  1 
  | (ins_br_neg) op == 45 & ext_20 ==  1 & f_19 ==  1 
  | (ins_br_neg) op == 44 & ext_20 ==  0 & f_19 ==  1 
  | (ins_br_neg) op == 44 & ext_20 ==  1 & f_19 ==  1 
  | (ins_br_neg) op == 37 & ext_20 ==  0 & f_19 ==  1 
  | (ins_br_neg) op == 37 & ext_20 ==  1 & f_19 ==  1 
  | (ins_br_neg) op == 36 & f_19 ==  1 
  | (ADDBF) op == 42 
  | (ADDIBF) op == 43 
  | (ins_br_neg) op == 50 & c1_16 ==  1 
  | (ins_br_neg) op == 51 & c1_16 ==  1 
  | (ins_br_neg) op == 59 & c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  0 & p_20 ==  0 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 52 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  0 & p_20 ==  1 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  1 & p_20 ==  0 & se_21 ==  0 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  1 & 
  c3_16 ==  1 
  | (ins_br_neg) op == 53 & cl_19 ==  1 & p_20 ==  1 & se_21 ==  0 & c3_16 ==  1

***********/
c_c_n_Instance c_c_neg(void) {
  c_c_n_Instance _i = { c_c_neg_TAG };
  return _i;
}
/**************

